declare module "@env" {
  export const IPA_BASE: string;
  export const API_BASE_URL: string;
  export const API_TIMEOUT: string;
  export const ENVIRONMENT: string;
  export const LOGIN: string;
  export const REFRESH_TOKEN: string;
  export const REGISTER: string;
  export const REVENUE_TEST: string;
  export const REVENUE_API_ANDROID: string;
  export const REVENUE_API_APPLE: string;
  export const GET_PLAN: string;
  export const IMAGE_UPLOAD: string;
  export const SET_GOALS: string;
  export const DAILY_TRACK: string;
  export const WORKOUT_DONE: string;
  export const OTP_AUTH: string;
  export const FORGOT_PASSWORD: string;
  export const LOG_OUT: string;
  export const RESEND_OTP: string;
  export const RESET_PASSWORD: string;
}
